function category({ id, label, parent, query, accent, description }) {
  return {
    id,
    label,
    parent,
    query,
    accent,
    description,
  };
}

// This file contains category metadata and query vocabulary only. The topic
// arrays below are legacy authoring notes; ingestion never exposes them as
// cards and only publishes records grounded in the current source snapshot.
export const additionalNicheCategories = [
  category({
    id: "pop",
    label: "Pop",
    parent: "Music",
    query: "pop music new release viral song chart",
    accent: "#ff4f86",
    description: "Hooks, releases, fandom moments, and pop-cultural signals that are moving faster than the general song leaderboard.",
    topics: [
      { title: "The hook is back in the driver's seat", description: "Pop's most durable moments still begin with a line or melody people can carry into a group chat, a short clip, or a whole room.", whyNow: "Fresh releases and replayed hooks are creating a second wave of discovery this week.", url: "https://www.billboard.com/charts/pop-songs/", source: "Billboard Pop", sourceLabel: "Browse the chart", image: "/culture/song-petal-ariana-grande.webp", trendLabel: "Hook first" },
      { title: "Deluxe tracks are a second campaign", description: "A bonus track is no longer just an extra: it can reset the visual language, reopen a rollout, and give fans a new favorite to organize around.", whyNow: "Recent deluxe drops are extending release conversations well past their first weekend.", url: "https://www.billboard.com/charts/hot-100/", source: "Billboard Hot 100", sourceLabel: "See the signal", image: "/culture/song-stupid-song-olivia-rodrigo.webp", trendLabel: "Second wind" },
      { title: "Pop fandom is writing the rollout", description: "Fan edits, dance formats, and lyric fragments are shaping which part of a polished pop release becomes the public-facing moment.", whyNow: "This week's most shared pop moments are being selected in the feed before they settle on a chart.", url: "https://newsroom.tiktok.com/en-us/music", source: "TikTok Music", sourceLabel: "Read the trend desk", image: "/culture/song-hate-that-i-made-you-love-me-ariana-grande.webp", trendLabel: "Fandom cut" },
    ],
  }),
  category({
    id: "hip-hop-rap",
    label: "Hip-hop & rap",
    parent: "Music",
    query: "hip hop rap new music freestyle album release",
    accent: "#f15b40",
    description: "Verses, producers, mixtapes, and rap conversations gaining lift before they settle into the mainstream cycle.",
    topics: [
      { title: "The verse is back in the group chat", description: "A sharp verse can now travel as a self-contained event, carrying cadence, punchlines, and a producer's whole atmosphere in under a minute.", whyNow: "New clips and guest verses are pulling attention toward writing and delivery again this week.", url: "https://www.billboard.com/charts/hot-rap-songs/", source: "Billboard Hot Rap Songs", sourceLabel: "Browse the chart", image: "/culture/song-choosin-texas-ella-langley.webp", trendLabel: "Bars in motion" },
      { title: "Mixtape energy meets rollout discipline", description: "Artists are pairing loose, immediate tracks with highly designed worlds, making the project feel spontaneous and collectible at the same time.", whyNow: "The week's rap conversation is clustering around projects that feel both raw and carefully sequenced.", url: "https://www.complex.com/music", source: "Complex Music", sourceLabel: "Read the coverage", image: "/culture/song-earrings-malcolm-todd.webp", trendLabel: "Loose but precise" },
      { title: "The producer tag is a personality", description: "A familiar tag or drum pocket can function like a signature, letting listeners recognize a collaboration before the artist even enters the frame.", whyNow: "Producer-led clips are turning behind-the-scenes details into front-of-feed conversation.", url: "https://genius.com/", source: "Genius", sourceLabel: "Follow the annotations", image: "/culture/person-andrew-tate.webp", trendLabel: "Signature sound" },
    ],
  }),
  category({
    id: "r-and-b-soul",
    label: "R&B & soul",
    parent: "Music",
    query: "R&B soul music new release vocal performance",
    accent: "#b76bff",
    description: "Vocal performances, slow-burn releases, and soul references that are finding a fresh audience beyond the broad music charts.",
    topics: [
      { title: "Late-night R&B is finding daylight", description: "Intimate production and close-up vocals are traveling outside their usual listening hours, becoming the soundtrack for edits, routines, and quiet flexes.", whyNow: "A cluster of low-key releases is gaining replay through mood-first discovery this week.", url: "https://www.billboard.com/charts/r-and-b-hip-hop-songs/", source: "Billboard R&B/Hip-Hop", sourceLabel: "Browse the chart", image: "/culture/song-earrings-malcolm-todd.webp", trendLabel: "After-hours lift" },
      { title: "The vocal run becomes a shareable event", description: "Listeners are isolating the exact moment a singer bends, stacks, or stretches a phrase and turning technique into the hook itself.", whyNow: "Performance snippets are sending people back to full songs for the vocal detail they caught in passing.", url: "https://www.npr.org/music/", source: "NPR Music", sourceLabel: "Explore the performances", image: "/culture/song-babydoll-dominic-fike.webp", trendLabel: "Voice as headline" },
      { title: "Soul samples are back in rotation", description: "Classic textures are being reintroduced with enough space to feel familiar without becoming a museum piece, keeping the old reference alive in a new room.", whyNow: "Sample-spotting threads are giving this week's songs a second layer of conversation.", url: "https://open.spotify.com/genre/rnb-page", source: "Spotify R&B", sourceLabel: "Listen to the lane", image: "/culture/song-man-i-need-olivia-dean.webp", trendLabel: "Old soul, new room" },
    ],
  }),
  category({
    id: "indie-alternative",
    label: "Indie & alternative",
    parent: "Music",
    query: "indie alternative rock new music festival discovery",
    accent: "#6c9e7b",
    description: "Guitar lines, left-field pop, and scene-level discoveries that are building momentum before a wider breakout.",
    topics: [
      { title: "Guitar bands are reclaiming the small room", description: "The new alternative fantasy is less about maximal production and more about a song that feels better when a crowd is close enough to sing every turn.", whyNow: "Live clips and intimate sessions are pushing guitar-forward acts into new discovery loops.", url: "https://www.nme.com/music", source: "NME", sourceLabel: "Read the scene report", image: "/culture/song-loser-tame-impala.webp", trendLabel: "Small room energy" },
      { title: "The quiet chorus gets loud online", description: "Subtle vocal turns and understated choruses are becoming the part listeners quote, remix, and build a visual mood around.", whyNow: "Low-key tracks are gaining lift through repeat listens rather than one oversized viral moment.", url: "https://www.stereogum.com/", source: "Stereogum", sourceLabel: "Follow the discoveries", image: "/culture/song-self-aware-temper-city.webp", trendLabel: "Soft breakout" },
      { title: "Festival discovery starts before the set", description: "Playlists, rehearsal snippets, and fan-shot previews now let listeners arrive at a festival with a personal shortlist of artists they have only just found.", whyNow: "This week's festival conversation is sending attention toward the names just outside the obvious headliners.", url: "https://www.brooklynvegan.com/", source: "BrooklynVegan", sourceLabel: "Browse the live radar", image: "/culture/song-hate-that-i-made-you-love-me-ariana-grande.webp", trendLabel: "Before the stage" },
    ],
  }),
  category({
    id: "latin-music",
    label: "Latin music",
    parent: "Music",
    query: "Latin music reggaeton regional Mexican new release",
    accent: "#f28d45",
    description: "Reggaetón, música Mexicana, bachata, and cross-border sounds with momentum outside a single-language chart.",
    topics: [
      { title: "Regional sounds keep crossing the border", description: "Accordion lines, corridos, and regional instruments are moving through global playlists without sanding down the local identity that made them distinct.", whyNow: "The latest releases are making regional texture part of the international pop conversation.", url: "https://www.billboard.com/charts/latin-songs/", source: "Billboard Latin", sourceLabel: "Browse the chart", image: "/culture/person-shakira.webp", trendLabel: "Borderless sound" },
      { title: "The dance-floor bridge is doing the work", description: "A strong rhythmic switch can connect club music, pop, and regional styles in a way that gives listeners an immediate entry point.", whyNow: "Dance clips are turning genre-blending moments into the most portable part of this week's releases.", url: "https://www.billboard.com/charts/latin-airplay/", source: "Billboard Latin Airplay", sourceLabel: "See the movement", image: "/culture/song-animal-katseye.webp", trendLabel: "Rhythm crossover" },
      { title: "Spanglish is a hook strategy", description: "Bilingual phrases are being used as texture, punchline, and invitation, letting a chorus feel specific while still opening the door to a wider singalong.", whyNow: "Mixed-language hooks are showing up repeatedly in the clips traveling furthest this week.", url: "https://www.rollingstone.com/music/music-latin/", source: "Rolling Stone Música", sourceLabel: "Read the coverage", image: "/culture/song-man-i-need-olivia-dean.webp", trendLabel: "Two-language hook" },
    ],
  }),
  category({
    id: "country",
    label: "Country",
    parent: "Music",
    query: "country music new release Nashville singer songwriter",
    accent: "#c88948",
    description: "Story songs, Nashville craft, crossover production, and the country artists building momentum outside the general song chart.",
    topics: [
      { title: "Country is stretching its map", description: "Country's current edge is a wide one: traditional storytelling, rock muscle, pop polish, and regional details can all belong in the same week.", whyNow: "New releases are making genre boundaries part of the conversation instead of a footnote.", url: "https://www.billboard.com/charts/country-songs/", source: "Billboard Country", sourceLabel: "Browse the chart", image: "/culture/song-choosin-texas-ella-langley.webp", trendLabel: "Wide-open lane" },
      { title: "The story song is social content", description: "A single lyric can now introduce a character, a hometown, and an emotional plot before someone has heard the full arrangement.", whyNow: "Lyric-led clips are sending listeners from a short scene directly into full country releases.", url: "https://www.rollingstone.com/music/music-country/", source: "Rolling Stone Country", sourceLabel: "Read the latest", image: "/culture/song-stupid-song-olivia-rodrigo.webp", trendLabel: "Verse to feed" },
      { title: "Honky-tonk details, stadium scale", description: "The most shareable country moments are pairing tactile details—boots, bars, back roads—with choruses built to fill a much bigger room.", whyNow: "Live videos are making the scale of this week's country breakouts impossible to miss.", url: "https://www.cmt.com/music", source: "CMT Music", sourceLabel: "Watch the performances", image: "/culture/person-taylor-swift.webp", trendLabel: "Big room roots" },
    ],
  }),
  category({
    id: "afrobeats",
    label: "Afrobeats",
    parent: "Music",
    query: "Afrobeats Afropop music new release dance trend",
    accent: "#f3b341",
    description: "Afropop releases, dance-led discovery, and global collaborations that are building momentum from the rhythm outward.",
    topics: [
      { title: "The groove travels without translation", description: "A drum pattern, vocal pocket, and movement can make a song legible across borders before listeners know every word.", whyNow: "This week's discovery clips are rewarding songs whose rhythm does the introduction first.", url: "https://www.billboard.com/charts/world-digital-song-sales/", source: "Billboard Global", sourceLabel: "See the chart", image: "/culture/song-animal-katseye.webp", trendLabel: "Rhythm first" },
      { title: "Afropop hooks are global chorus material", description: "Collaborations are treating the chorus as shared space, keeping a song's local character while giving multiple audiences a line to carry.", whyNow: "Cross-border features are appearing across the week's most replayed music clips.", url: "https://www.okayafrica.com/music/", source: "OkayAfrica Music", sourceLabel: "Read the scene report", image: "/culture/person-shakira.webp", trendLabel: "Worldwide chorus" },
      { title: "Dance challenges are scouting A&R", description: "Movement is acting as an early signal for which songs have enough personality to survive outside the original release context.", whyNow: "Dance formats are giving newer artists a discovery path that bypasses the broad chart cycle.", url: "https://www.youtube.com/results?search_query=afrobeats+new+music", source: "YouTube", sourceLabel: "Watch the movement", image: "/culture/song-babydoll-dominic-fike.webp", trendLabel: "Move before chart" },
    ],
  }),
  category({
    id: "basketball",
    label: "Basketball",
    parent: "Sports",
    query: "basketball NBA WNBA players playoffs trade news",
    accent: "#ed7a36",
    description: "The players, schemes, roster moves, and basketball culture stories worth knowing beyond the final score.",
    topics: [
      { title: "The next guard conversation", description: "Young guards are being evaluated through a wider lens now: shot creation, decision-making, defensive range, and whether their style survives a playoff possession.", whyNow: "Off-season movement and international play are resetting the league's next-wave debates.", url: "https://www.espn.com/nba/", source: "ESPN NBA", sourceLabel: "Follow the league", image: "/culture/person-lamine-yamal.webp", trendLabel: "Next up" },
      { title: "Positionless basketball gets specific", description: "The phrase only matters when a player can solve several problems in the same lineup, turning versatility into an actual tactical advantage.", whyNow: "Recent analysis is focusing on the exact roles that make flexible lineups work.", url: "https://www.nytimes.com/athletic/nba/", source: "The Athletic NBA", sourceLabel: "Read the analysis", image: "/culture/person-erling-haaland.webp", trendLabel: "Role matters" },
      { title: "The highlight has a scouting report", description: "A spectacular finish now travels with a second conversation about footwork, spacing, and the small decision that made the clip possible.", whyNow: "Breakout clips are pulling casual viewers into deeper basketball vocabulary this week.", url: "https://www.wnba.com/", source: "WNBA", sourceLabel: "See the game", image: "/culture/meme-mbappe-special.webp", trendLabel: "More than a clip" },
    ],
  }),
  category({
    id: "baseball",
    label: "Baseball",
    parent: "Sports",
    query: "MLB baseball games trade prospects home run news",
    accent: "#4d83d1",
    description: "Pitching matchups, prospects, trades, and the small statistical details making baseball feel immediate this week.",
    topics: [
      { title: "The pitch clock changed the highlight", description: "Baseball's new rhythm is making the space between pitches part of the spectacle, with urgency showing up before the ball is put in play.", whyNow: "Recent games and broadcasts are drawing attention to pace as a piece of player identity.", url: "https://www.mlb.com/news", source: "MLB News", sourceLabel: "Follow the league", image: "/culture/news-city-to-close-non-essential-offices-and-services-monday-followin.webp", trendLabel: "Faster tension" },
      { title: "Prospects are becoming content", description: "Minor-league call-ups and scouting reports now arrive with clips, personality, and a ready-made story about what a player might change next.", whyNow: "The week's roster conversations are making future stars feel like current events.", url: "https://www.baseballamerica.com/", source: "Baseball America", sourceLabel: "Track the prospects", image: "/culture/person-jeff-bezos.webp", trendLabel: "Future in frame" },
      { title: "The long ball is a full production", description: "A home run is now the payoff to a chain of decisions: pitch selection, count management, launch angle, and the crowd's anticipation.", whyNow: "Highlight packages are sending viewers back to the at-bat rather than stopping at the result.", url: "https://www.espn.com/mlb/", source: "ESPN MLB", sourceLabel: "See the matchups", image: "/culture/person-lamine-yamal.webp", trendLabel: "At-bat drama" },
    ],
  }),
  category({
    id: "american-football",
    label: "American football",
    parent: "Sports",
    query: "NFL football quarterback training camp draft trade news",
    accent: "#31896e",
    description: "Quarterbacks, roster battles, scheme shifts, and football stories that matter before the national broadcast catches up.",
    topics: [
      { title: "Training camp is already a narrative engine", description: "A rep count, a new route combination, or one sharp practice clip can become the first chapter of an entire season's storyline.", whyNow: "Camp reports and preseason footage are turning possibility into daily football conversation.", url: "https://www.espn.com/nfl/", source: "ESPN NFL", sourceLabel: "Follow camp", image: "/culture/news-ice-cream-company-rebel-filed-for-chapter-11-bankruptcy.webp", trendLabel: "Before kickoff" },
      { title: "The quarterback carousel keeps spinning", description: "Every new starter changes the story around protection, play-calling, expectations, and which part of a roster has to grow up fastest.", whyNow: "Depth-chart movement is creating more meaningful football questions than a simple win-loss prediction.", url: "https://www.nfl.com/news", source: "NFL News", sourceLabel: "Read the latest", image: "/culture/person-taylor-swift.webp", trendLabel: "New signal caller" },
      { title: "Fantasy football starts in the rumor cycle", description: "Usage hints, red-zone roles, and coach comments give fantasy players a way to read a season before the box score can confirm anything.", whyNow: "Early rankings are being rebuilt around training-camp clues and emerging role changes.", url: "https://www.fantasypros.com/nfl/", source: "FantasyPros NFL", sourceLabel: "Track the roles", image: "/culture/news-city-to-close-non-essential-offices-and-services-monday-followin.webp", trendLabel: "Role watch" },
    ],
  }),
  category({
    id: "tennis",
    label: "Tennis",
    parent: "Sports",
    query: "tennis ATP WTA tournament players match news",
    accent: "#9aaa32",
    description: "Tournament swings, player rivalries, surfaces, and the tactical turns shaping tennis beyond the headline final.",
    topics: [
      { title: "Hard-court season resets the hierarchy", description: "A new surface changes the questions: who can take time away, who can defend deep, and whose second serve holds under pressure.", whyNow: "The calendar's next turn is putting recent results in a different tactical light.", url: "https://www.atptour.com/en/news", source: "ATP Tour", sourceLabel: "Follow the tour", image: "/culture/person-lamine-yamal.webp", trendLabel: "New surface" },
      { title: "Teen contenders are forcing the question", description: "A young player's run is compelling when it reveals more than potential—especially a pattern they can repeat against experienced opponents.", whyNow: "Breakthrough matches are making the next generation feel immediate rather than theoretical.", url: "https://www.wtatennis.com/news", source: "WTA", sourceLabel: "Read the tour notes", image: "/culture/person-erling-haaland.webp", trendLabel: "Future now" },
      { title: "The rally is the highlight", description: "Long exchanges are being edited like action sequences, with defense, recovery, and the final change of direction carrying the drama.", whyNow: "Point-of-the-match clips are bringing tactical tennis to viewers who may not watch an entire draw.", url: "https://www.youtube.com/results?search_query=tennis+best+rallies", source: "YouTube Tennis", sourceLabel: "Watch the points", image: "/culture/person-shakira.webp", trendLabel: "Point by point" },
    ],
  }),
  category({
    id: "motorsport",
    label: "Motorsport",
    parent: "Sports",
    query: "Formula 1 racing motorsport driver team race news",
    accent: "#e74b50",
    description: "Drivers, garages, strategy, and the data-rich drama that makes a motorsport weekend feel like a serialized show.",
    topics: [
      { title: "Qualifying is the weekend's cliffhanger", description: "A single lap can reveal setup choices, tire confidence, and the pressure a driver will carry into the race before the lights even go out.", whyNow: "Recent qualifying battles are making Saturday performance part of the main storyline.", url: "https://www.formula1.com/en/latest", source: "Formula 1", sourceLabel: "Follow the paddock", image: "/culture/product-galaxy-z-fold-8.webp", trendLabel: "One-lap drama" },
      { title: "The garage becomes the storyline", description: "Strategy calls, upgrades, and team radio turn engineering decisions into character beats that fans can follow race by race.", whyNow: "Behind-the-scenes coverage is making the team battle as legible as the driver standings.", url: "https://www.motorsport.com/f1/", source: "Motorsport.com", sourceLabel: "Read the analysis", image: "/culture/media-odyssey.webp", trendLabel: "Inside the garage" },
      { title: "Data is part of the fandom", description: "Telemetry, tire windows, and lap deltas let viewers build an argument about what happened instead of settling for the final order.", whyNow: "Explainer clips are turning technical details into the most satisfying part of the week's race recap.", url: "https://www.racefans.net/", source: "RaceFans", sourceLabel: "Decode the race", image: "/culture/person-jeff-bezos.webp", trendLabel: "Numbers at speed" },
    ],
  }),
  category({
    id: "golf",
    label: "Golf",
    parent: "Sports",
    query: "golf PGA tour major tournament players news",
    accent: "#5d9f63",
    description: "Courses, swings, equipment, and tournament storylines that make golf more interesting than a leaderboard alone.",
    topics: [
      { title: "The leaderboard is a moving target", description: "Golf's most suspenseful turns come from how a course changes across the day, making patience, weather, and late pressure part of the competition.", whyNow: "The latest tournament finishes are rewarding viewers who follow the round's shape, not just its winner.", url: "https://www.pgatour.com/news", source: "PGA Tour", sourceLabel: "Follow the tour", image: "/culture/person-erling-haaland.webp", trendLabel: "Course in motion" },
      { title: "Equipment talk is spectator sport", description: "A club change or ball choice becomes compelling when it clarifies the player's strategy instead of functioning as a simple product plug.", whyNow: "Gear stories are being tied to visible changes in shot shape and confidence this week.", url: "https://www.golfdigest.com/gear", source: "Golf Digest", sourceLabel: "Read the gear desk", image: "/culture/product-dasein-women-s-tote-bag.webp", trendLabel: "Gear with a reason" },
      { title: "The next generation plays loud", description: "Younger golfers are bringing faster pacing, visible emotion, and a more social presentation to a sport built on quiet concentration.", whyNow: "New players are drawing attention for the way they change the atmosphere around a competitive round.", url: "https://www.golfchannel.com/news", source: "Golf Channel", sourceLabel: "Watch the rise", image: "/culture/person-sonam-wangchuk.webp", trendLabel: "New tempo" },
    ],
  }),
  category({
    id: "sports-news",
    label: "Sports news",
    parent: "Sports",
    query: "sports news leagues athletes trades results headlines",
    accent: "#2f8db0",
    description: "The cross-sport storylines, business moves, and athlete moments that deserve a wider lens than one league provides.",
    topics: [
      { title: "The calendar is the story", description: "A crowded sports week can connect tournaments, transfers, injuries, and cultural moments that would otherwise stay in separate league silos.", whyNow: "This week's biggest sports conversations are crossing the boundaries between seasons and competitions.", url: "https://www.espn.com/", source: "ESPN", sourceLabel: "See the whole board", image: "/culture/meme-mbappe-special.webp", trendLabel: "Beyond one league" },
      { title: "The transaction wire is never quiet", description: "Trades, signings, and contract decisions reshape what fans expect from a season before a single new game has been played.", whyNow: "A cluster of roster moves is changing multiple title pictures at once.", url: "https://sports.yahoo.com/", source: "Yahoo Sports", sourceLabel: "Follow the moves", image: "/culture/news-ufc-330-makhachev-secures-record-setting-win-against-machado-gar.webp", trendLabel: "Roster ripple" },
      { title: "Fans want the why after the score", description: "The result is the entry point; the more useful story explains the tactical choice, injury, matchup, or organizational decision behind it.", whyNow: "Explainers are carrying more of the postgame conversation than raw highlights alone.", url: "https://www.cbssports.com/", source: "CBS Sports", sourceLabel: "Read the explainers", image: "/culture/person-lamine-yamal.webp", trendLabel: "Context after impact" },
    ],
  }),
  category({
    id: "us-news",
    label: "U.S. news",
    parent: "News",
    query: "United States news policy courts public life latest",
    accent: "#5c78b9",
    description: "U.S. developments, public decisions, and local-to-national stories with consequences beyond the general news leaderboard.",
    topics: [
      { title: "The policy headline meets the kitchen table", description: "The most useful domestic stories connect a government decision to the ordinary systems people actually use: work, school, housing, health, or travel.", whyNow: "This week's national coverage is being measured by its practical consequence, not just its political drama.", url: "https://apnews.com/hub/us-news", source: "Associated Press U.S.", sourceLabel: "Read the coverage", image: "/culture/news-city-to-close-non-essential-offices-and-services-monday-followin.webp", trendLabel: "Life after headline" },
      { title: "Courts are setting the next headline", description: "Legal decisions often arrive as quiet documents before becoming public turning points, changing what agencies, companies, and communities can do next.", whyNow: "A run of rulings is moving several national conversations from argument into implementation.", url: "https://www.reuters.com/world/us/", source: "Reuters U.S.", sourceLabel: "Follow the decisions", image: "/culture/news-egg-recall-over-salmonella-deemed-class-i-by-the-fda-see-the-ful.webp", trendLabel: "Decision point" },
      { title: "Weather keeps rewriting the local agenda", description: "Storms and heat turn infrastructure, public safety, and preparation into immediate civic stories long before the season has finished.", whyNow: "Recent weather coverage is pulling local impacts into national attention.", url: "https://www.weather.gov/news", source: "National Weather Service", sourceLabel: "Track the conditions", image: "/culture/news-hurricane-lala-passes-big-island-hawai-i-spared-from-direct-hit.webp", trendLabel: "Local, then national" },
    ],
  }),
  category({
    id: "world-news",
    label: "World news",
    parent: "News",
    query: "world international news diplomacy conflict economy latest",
    accent: "#4b9b9b",
    description: "International developments, diplomacy, and regional stories that are changing how the wider world is being read this week.",
    topics: [
      { title: "The map keeps moving", description: "International stories become easier to understand when the timeline, the neighboring interests, and the people living with the decision are visible together.", whyNow: "A burst of diplomatic and regional coverage is making the consequences of movement impossible to isolate.", url: "https://www.reuters.com/world/", source: "Reuters World", sourceLabel: "Read the world desk", image: "/culture/person-sonam-wangchuk.webp", trendLabel: "A wider frame" },
      { title: "Diplomacy becomes a live sport", description: "Meetings, statements, and carefully chosen absences can signal the next move before any formal agreement is announced.", whyNow: "This week's coverage is following the language around negotiations as closely as the outcomes.", url: "https://apnews.com/world-news", source: "Associated Press World", sourceLabel: "Follow the negotiations", image: "/culture/news-hurricane-lala-leaves-big-island-residents-in-hawaii-hunkered-do.webp", trendLabel: "Between the lines" },
      { title: "A regional story goes global", description: "A local event can suddenly matter everywhere when it touches supply chains, migration, climate, security, or a shared cultural conversation.", whyNow: "Several stories this week are being understood through their second-order effects outside the original region.", url: "https://www.bbc.com/news/world", source: "BBC World", sourceLabel: "See the wider context", image: "/culture/person-jeff-bezos.webp", trendLabel: "Ripple effect" },
    ],
  }),
  category({
    id: "business-markets",
    label: "Business & markets",
    parent: "News",
    query: "business markets economy companies stocks latest news",
    accent: "#3d907b",
    description: "Companies, markets, labor, and consumer signals that explain what is changing beneath the day's broad business headlines.",
    topics: [
      { title: "Markets are pricing the next question", description: "A market move is most useful as a prompt: what changed in expectations about rates, demand, risk, or a company's ability to execute?", whyNow: "This week's volatility is being read as a story about future confidence rather than a verdict on one day.", url: "https://www.reuters.com/markets/", source: "Reuters Markets", sourceLabel: "Follow the markets", image: "/culture/news-ice-cream-company-rebel-filed-for-chapter-11-bankruptcy.webp", trendLabel: "Expectation watch" },
      { title: "The consumer signal matters", description: "Spending patterns, product queues, and the small trade-offs people make can reveal a shift in confidence before a quarterly report explains it.", whyNow: "Recent retail and household stories are making everyday behavior part of the market read.", url: "https://www.wsj.com/news/business", source: "The Wall Street Journal", sourceLabel: "Read the business desk", image: "/culture/product-restocked-wirkin-bag.webp", trendLabel: "In the checkout" },
      { title: "AI spending meets the balance sheet", description: "The business question is moving from whether companies will use AI to where the investment is producing measurable work, revenue, or leverage.", whyNow: "Earnings and product updates are putting practical return on AI spend in the foreground.", url: "https://www.ft.com/technology", source: "Financial Times", sourceLabel: "Follow the technology economy", image: "/culture/product-galaxy-z-fold-8.webp", trendLabel: "Show the return" },
    ],
  }),
  category({
    id: "science-space",
    label: "Science & space",
    parent: "News",
    query: "science space NASA discovery research latest news",
    accent: "#7169c7",
    description: "Space missions, research breakthroughs, and scientific ideas that are becoming part of the public conversation now.",
    topics: [
      { title: "The sky is the next timeline", description: "Space stories make distant systems feel immediate when a new image, mission, or measurement turns an abstract question into something people can see.", whyNow: "Fresh observations and mission updates are giving this week's science conversation a visual center.", url: "https://www.nasa.gov/news/", source: "NASA", sourceLabel: "Follow the mission desk", image: "/culture/media-odyssey.webp", trendLabel: "Look up" },
      { title: "Tiny instruments, big discoveries", description: "Many breakthroughs begin with better sensors, cleaner samples, or a more patient way of measuring something researchers have been chasing for years.", whyNow: "New research coverage is highlighting the tools behind the result as much as the result itself.", url: "https://www.sciencenews.org/", source: "Science News", sourceLabel: "Read the research", image: "/culture/product-galaxy-z-fold-8.webp", trendLabel: "Better measurement" },
      { title: "Science gets a public beta", description: "When a complex finding is explained with an image, model, or experiment people can understand, the research becomes a shared object rather than a distant paper.", whyNow: "This week's most shared science stories are the ones that make the method visible.", url: "https://www.nature.com/news", source: "Nature News", sourceLabel: "Explore the evidence", image: "/culture/news-moderna-stock-explodes-over-100-after-cancer-vaccine-breakthroug.webp", trendLabel: "Method matters" },
    ],
  }),
  category({
    id: "climate-environment",
    label: "Climate & environment",
    parent: "News",
    query: "climate environment extreme weather energy conservation latest news",
    accent: "#4d9e79",
    description: "Weather, ecosystems, energy, and adaptation stories that make the climate conversation concrete and local.",
    topics: [
      { title: "Extreme weather is the backdrop", description: "The climate story is increasingly told through the systems people rely on: roads, power, crops, insurance, and the timing of everyday life.", whyNow: "Recent conditions are turning long-term climate questions into immediate planning stories.", url: "https://climate.nasa.gov/news/", source: "NASA Climate", sourceLabel: "Read the context", image: "/culture/news-hurricane-lala-leaves-big-island-residents-in-hawaii-hunkered-do.webp", trendLabel: "Now, not abstract" },
      { title: "The grid is becoming a culture story", description: "Power demand, storage, and local infrastructure are shaping where people live, what gets built, and how technology fits into the day.", whyNow: "Energy stories are showing up across business, policy, and consumer coverage this week.", url: "https://www.noaa.gov/climate", source: "NOAA Climate", sourceLabel: "Follow the data", image: "/culture/news-city-to-close-non-essential-offices-and-services-monday-followin.webp", trendLabel: "Power in focus" },
      { title: "Adaptation is moving local", description: "The most legible environmental changes are often neighborhood-scale: shade, water, food systems, building materials, and the design of public space.", whyNow: "Local experiments are giving the week's climate conversation practical examples instead of only distant targets.", url: "https://www.theguardian.com/environment/climate-crisis", source: "The Guardian Environment", sourceLabel: "See the experiments", image: "/culture/media-odyssey.webp", trendLabel: "Built for change" },
    ],
  }),
  category({
    id: "health",
    label: "Health",
    parent: "News",
    query: "health medicine public health research wellness latest news",
    accent: "#d96878",
    description: "Medical research, public health, prevention, and everyday health stories with clear relevance beyond generic wellness content.",
    topics: [
      { title: "Prevention is having a data moment", description: "Health coverage is increasingly about finding risk earlier, making care easier to reach, and giving people signals they can act on before a crisis.", whyNow: "New research and public guidance are pushing prevention back into the center of the conversation.", url: "https://www.cdc.gov/media/", source: "CDC Newsroom", sourceLabel: "Read the guidance", image: "/culture/news-egg-recall-over-salmonella-deemed-class-i-by-the-fda-see-the-ful.webp", trendLabel: "Earlier action" },
      { title: "The wellness claim meets evidence", description: "The useful question behind a viral health idea is what was actually studied, for whom, and what would count as a meaningful result.", whyNow: "This week's health discourse is separating attractive routines from claims that have real support.", url: "https://www.nih.gov/news-events/news-releases", source: "National Institutes of Health", sourceLabel: "Check the evidence", image: "/culture/news-moderna-stock-explodes-over-100-after-cancer-vaccine-breakthroug.webp", trendLabel: "Proof over promise" },
      { title: "Public health becomes personal", description: "A population-level update matters most when it explains the small decisions people can make about prevention, exposure, treatment, or access.", whyNow: "Recent coverage is translating broad health signals into more practical individual context.", url: "https://www.who.int/news", source: "World Health Organization", sourceLabel: "Read the health desk", image: "/culture/product-starbucks-unicorn-frappuccino.webp", trendLabel: "Make it usable" },
    ],
  }),
  category({
    id: "tech-news",
    label: "Technology news",
    parent: "News",
    query: "technology AI gadgets companies regulation latest news",
    accent: "#4d91d8",
    description: "The consequential technology stories—products, platforms, regulation, and research—separated from general gadget discovery.",
    topics: [
      { title: "The AI product cycle gets practical", description: "The interesting question is shifting from what a model can demonstrate to where a real workflow becomes faster, clearer, or newly possible.", whyNow: "New product launches and user experiments are making practical adoption the week's main technology signal.", url: "https://www.theverge.com/ai-artificial-intelligence", source: "The Verge AI", sourceLabel: "Read the coverage", image: "/culture/product-galaxy-z-fold-8.webp", trendLabel: "Useful by Tuesday" },
      { title: "Antitrust becomes product news", description: "Regulation can change the interfaces, defaults, pricing, and choices people experience every day—not just the companies named in a case.", whyNow: "Recent legal and policy moves are making platform structure part of mainstream product conversation.", url: "https://www.reuters.com/technology/", source: "Reuters Technology", sourceLabel: "Follow the policy", image: "/culture/media-odyssey.webp", trendLabel: "Rules shape tools" },
      { title: "The hardware reset", description: "The next device story is less about adding one more feature and more about making form, battery, camera, and software feel like one coherent behavior.", whyNow: "New device coverage is rewarding products that change how a task feels, not only what a spec sheet says.", url: "https://www.wired.com/", source: "WIRED", sourceLabel: "Read technology coverage", image: "/culture/product-galaxy-z-fold-8.webp", trendLabel: "Form meets function" },
    ],
  }),
  category({
    id: "entertainment-news",
    label: "Entertainment news",
    parent: "News",
    query: "entertainment news celebrity film television music industry latest",
    accent: "#c968b8",
    description: "Casting, releases, industry moves, and entertainment moments that sit between culture chatter and hard news.",
    topics: [
      { title: "The franchise machine is remixing itself", description: "Studios are looking for freshness inside familiar worlds, using new formats, tones, and points of view to make a known title feel newly discussable.", whyNow: "Announcements and first looks are making franchise strategy part of this week's entertainment story.", url: "https://variety.com/v/film/", source: "Variety Film", sourceLabel: "Read the industry desk", image: "/culture/movie-supergirl.webp", trendLabel: "Familiar, remixed" },
      { title: "Casting news is a social event", description: "A casting decision can instantly change the imagined tone of a project, creating a collaborative fan trailer before production is even visible.", whyNow: "Newly announced roles are generating more conversation about possibility than plot.", url: "https://www.hollywoodreporter.com/c/movies/", source: "The Hollywood Reporter", sourceLabel: "Follow the casting", image: "/culture/creator-zendaya.webp", trendLabel: "Before the trailer" },
      { title: "The release window is part of the story", description: "When and where a film, series, or special arrives now shapes how people discover it, talk about it, and decide whether it becomes a shared moment.", whyNow: "This week's release chatter is as focused on timing and access as it is on the title itself.", url: "https://www.indiewire.com/c/film/", source: "IndieWire", sourceLabel: "See what's arriving", image: "/culture/news-frozen-3-first-look-teases-anna-s-wedding-new-villain-more.webp", trendLabel: "Timing is content" },
    ],
  }),
  category({
    id: "home-design",
    label: "Home & design",
    parent: "Lifestyle",
    query: "home design interiors furniture architecture trend",
    accent: "#b68766",
    description: "Interiors, objects, architecture, and small design choices making everyday spaces feel newly legible or desirable.",
    topics: [
      { title: "Small spaces are getting smarter", description: "The best compact-home ideas do more than save room: they make storage, movement, and daily rituals feel intentional instead of compromised.", whyNow: "Space-saving layouts and flexible objects are dominating this week's design saves and shares.", url: "https://www.architecturaldigest.com/", source: "Architectural Digest", sourceLabel: "Browse the homes", image: "/culture/product-dasein-women-s-tote-bag.webp", trendLabel: "Room to move" },
      { title: "The color forecast is warmer", description: "Paint, upholstery, and small objects are being used to make a room feel collected and lived-in without committing to a full renovation.", whyNow: "Warm palettes are appearing across the week's most copied room details.", url: "https://www.domino.com/design/", source: "Domino", sourceLabel: "See the design ideas", image: "/culture/product-striped-canvas-mini-tote.webp", trendLabel: "Warmth, edited" },
      { title: "The object is the mood", description: "A single lamp, chair, textile, or table can set the emotional temperature of a space more effectively than a room full of matching pieces.", whyNow: "Object-first room tours are turning individual design choices into the new discovery format.", url: "https://www.dezeen.com/", source: "Dezeen", sourceLabel: "Explore the objects", image: "/culture/product-mystery-squishy-dumplings.webp", trendLabel: "One good object" },
    ],
  }),
  category({
    id: "travel",
    label: "Travel",
    parent: "Lifestyle",
    query: "travel destinations trip planning hotel food itinerary trend",
    accent: "#4ea5a2",
    description: "Destinations, itineraries, hotels, and travel behaviors that are making people rethink where and how to go next.",
    topics: [
      { title: "The destination is the itinerary", description: "Travelers are choosing places for the rhythm of a day—markets, swims, trains, walks, and late dinners—rather than a checklist of sights.", whyNow: "Itinerary-first guides are driving this week's travel inspiration more than landmark lists.", url: "https://www.cntraveler.com/", source: "Condé Nast Traveler", sourceLabel: "Find the route", image: "/culture/news-hurricane-lala-passes-big-island-hawai-i-spared-from-direct-hit.webp", trendLabel: "Day-shaped travel" },
      { title: "Shoulder season gets a glow-up", description: "The in-between months are becoming the point: lighter crowds, better light, and a version of a famous place that feels more inhabitable.", whyNow: "Recent destination coverage is selling timing and atmosphere as much as the destination itself.", url: "https://www.cntraveler.com/gallery/best-shoulder-season-destinations", source: "Condé Nast Traveler", sourceLabel: "See the timing guide", image: "/culture/person-sonam-wangchuk.webp", trendLabel: "Go between" },
      { title: "Travel planning becomes content", description: "Maps, packing systems, and tiny logistics are becoming satisfying objects to share, turning preparation into part of the trip's anticipation.", whyNow: "Planning videos and saveable guides are moving faster than traditional destination roundups.", url: "https://www.lonelyplanet.com/articles", source: "Lonely Planet", sourceLabel: "Browse the guides", image: "/culture/product-dasein-women-s-tote-bag.webp", trendLabel: "Before takeoff" },
    ],
  }),
  category({
    id: "wellness-fitness",
    label: "Wellness & fitness",
    parent: "Lifestyle",
    query: "fitness wellness exercise recovery sleep trend",
    accent: "#68a477",
    description: "Movement, recovery, sleep, and sustainable routines that are gaining traction beyond the broad wellness conversation.",
    topics: [
      { title: "Zone two refuses to disappear", description: "The appeal is less about a perfect protocol than a manageable way to build endurance into a routine without making every workout a test.", whyNow: "Low-intensity training is still circulating because it translates cleanly into repeatable weekly habits.", url: "https://www.runnersworld.com/uk/training/", source: "Runner's World", sourceLabel: "Read the training desk", image: "/culture/song-self-aware-temper-city.webp", trendLabel: "Repeatable effort" },
      { title: "Recovery is the new flex", description: "Rest, mobility, hydration, and sleep are being presented as active parts of performance rather than evidence that someone skipped the hard work.", whyNow: "Athlete and creator routines are putting recovery tools back in the center of the fitness feed.", url: "https://www.gq.com/about/fitness", source: "GQ Fitness", sourceLabel: "See the routines", image: "/culture/person-shakira.webp", trendLabel: "Train, then restore" },
      { title: "Short workouts, long streaks", description: "A smaller session can still feel complete when it is designed around consistency, a clear finish line, and a routine people can actually repeat.", whyNow: "Compact workout formats are gaining lift as people look for sustainable momentum rather than dramatic resets.", url: "https://www.self.com/fitness", source: "SELF Fitness", sourceLabel: "Find a routine", image: "/culture/product-starbucks-unicorn-frappuccino.webp", trendLabel: "Small, consistent" },
    ],
  }),
  category({
    id: "parenting",
    label: "Parenting",
    parent: "Lifestyle",
    query: "parenting family school kids advice trend",
    accent: "#e09a59",
    description: "Family systems, school rhythms, kid culture, and practical parenting conversations that are gaining attention right now.",
    topics: [
      { title: "The group chat is the village", description: "Parents are using small digital networks to trade logistics, reassurance, recommendations, and the kind of context that rarely fits a formal guide.", whyNow: "Back-to-school planning is making informal coordination feel newly visible this week.", url: "https://www.parents.com/", source: "Parents", sourceLabel: "Read the family desk", image: "/culture/book-theo-of-golden.webp", trendLabel: "Shared logistics" },
      { title: "Back-to-school is a systems problem", description: "The start of a school year is a choreography of sleep, supplies, transportation, meals, and emotions—not just a shopping list.", whyNow: "Seasonal preparation is pulling practical family routines into the center of the conversation.", url: "https://www.nytimes.com/section/parenting", source: "The New York Times Parenting", sourceLabel: "See the guides", image: "/culture/meme-homer-let-the-barts-out.webp", trendLabel: "Reset the rhythm" },
      { title: "Screen time is a design question", description: "The most useful family-tech conversations ask what a device is replacing, enabling, or interrupting instead of treating minutes as the whole story.", whyNow: "New family routines are focusing on the shape of digital life, not only its total duration.", url: "https://www.commonsensemedia.org/", source: "Common Sense Media", sourceLabel: "Find the context", image: "/culture/product-mystery-squishy-dumplings.webp", trendLabel: "Shape the habit" },
    ],
  }),
  category({
    id: "podcasts",
    label: "Podcasts",
    parent: "Culture",
    query: "podcast new episodes interview audio show trend",
    accent: "#8e6ed0",
    description: "Shows, formats, hosts, and episode moments that are making audio feel like a live part of culture again.",
    topics: [
      { title: "The video podcast is a set", description: "The most successful shows are designing a visual world—chairs, lighting, reactions, recurring bits—that makes the conversation recognizable before the clip begins.", whyNow: "This week's podcast clips are traveling because the format has a visual grammar, not just a famous guest.", url: "https://podcasts.apple.com/us/genre/podcasts/id26", source: "Apple Podcasts", sourceLabel: "Browse the charts", image: "/culture/creator-zendaya.webp", trendLabel: "More than audio" },
      { title: "Niche shows beat broad reach", description: "A focused show can build unusual trust by giving a specific community its own references, language, and long-running set of questions.", whyNow: "Specialist podcasts are gaining attention through recommendations that feel personal rather than mass-market.", url: "https://www.podchaser.com/", source: "Podchaser", sourceLabel: "Find a new show", image: "/culture/person-amelia-dimoldenberg.webp", trendLabel: "Specific wins" },
      { title: "The episode clip is its own format", description: "A good excerpt does not merely advertise the full episode; it has a beginning, a turn, and a reason to keep listening after the clip ends.", whyNow: "Short clips are driving discovery for shows whose full episodes live in a different attention mode.", url: "https://www.youtube.com/podcasts", source: "YouTube Podcasts", sourceLabel: "Watch the clips", image: "/culture/media-odyssey.webp", trendLabel: "Clip with a point" },
    ],
  }),
  category({
    id: "comedy",
    label: "Comedy",
    parent: "Culture",
    query: "comedy stand up sketch comedian viral bit",
    accent: "#e2a33f",
    description: "Bits, performers, formats, and comic phrases that are escaping their original stage or screen and becoming shared language.",
    topics: [
      { title: "The bit escapes the stage", description: "A strong comedy premise can now live as a stand-up clip, a caption, a reaction, and a repeated phrase without losing its original shape.", whyNow: "Short-form performances are turning this week's jokes into portable social objects.", url: "https://www.youtube.com/results?search_query=stand+up+comedy+new", source: "YouTube Comedy", sourceLabel: "Watch the bits", image: "/culture/person-amelia-dimoldenberg.webp", trendLabel: "Out of context" },
      { title: "Deadpan is having a loud week", description: "Understatement works best when the audience can see the absurdity gathering just beneath a calm delivery, making the smallest reaction feel huge.", whyNow: "Reaction-led clips are carrying more of the comedy conversation than polished punchline compilations.", url: "https://www.vulture.com/section/comedy", source: "Vulture Comedy", sourceLabel: "Read the comedy desk", image: "/culture/meme-best-of-zach.webp", trendLabel: "Quietly enormous" },
      { title: "Crowd work keeps traveling", description: "Audience interaction gives a comic an unpredictable scene and gives viewers the feeling that the joke is happening only once, right in front of them.", whyNow: "Crowd-work clips are creating discovery loops for performers beyond their scheduled specials.", url: "https://www.netflixisajoke.com/", source: "Netflix Is A Joke", sourceLabel: "Find a special", image: "/culture/meme-funky-ehh.webp", trendLabel: "One-night energy" },
    ],
  }),
];
